### PR TITLE
Add support for Almalinux 9

### PR DESCRIPTION
**Pull request by agaetep**

### CODE REVIEW

**Review by ramereth — CHANGES_REQUESTED** [review]
Please  update all the `kitchen.*.yml files` too.

**Review by ramereth — APPROVED** [review]
Patch bump

**Comment by agaetep** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v5.4.1.  Have a nice day!

**Pull request merged**
