### PR TITLE
Cthalmann/rubocop fixes

### PR DESCRIPTION
**Pull request by cthalmann**
Fixed rubocop errors.

@ramereth @armiller

### CODE REVIEW

**Comment by armiller** [comment]
@cthalmann I would go ahead and remove commit 7d8430e since it looks like none of the changes are being used.

**Comment by armiller** [comment]
👍

**Comment by ramereth** [comment]
@cthalmann can you update the Rakefile to include our standard set of things? When you run ``rake`` by itself, it should run the rubocop, foodcritic and rspec tests.

**Comment by fahlmant** [comment]
:+1:

**Pull request merged**
