### PR TITLE
Fahlmant/rubocop

### PR DESCRIPTION
**Pull request by fahlmant**

### CODE REVIEW

**Comment by armiller** [comment]
@fahlmant are you still working on this? I ran rubocop and got 191 offenses.

**Comment by fahlmant** [comment]
@armiller Do you want me to fix all the offenses in this PR too?

**Comment by rettigs** [comment]
Once I've finished up some of the other things I was working on, I was going to set up some tests and try and get the rdiff-backup cookbook 2.0 branch merged in, which will quite likely change the number of offenses significantly.  Having some better tests in place before applying so many changes would also help make sure nothing breaks.

**Comment by jordane** [comment]
@fahlmant Yes, fixing offenses in this PR would be good.

**Comment by rettigs** [comment]
I would hold off until 2.0 merged, since it would cause of ton of merge conflicts and all the work would be duplicated.

**Comment by fahlmant** [comment]
@retis Any ETA on 2.0?

**Comment by rettigs** [comment]
@fahlmant I'm thinking some time in the next few weeks.

**Comment by fahlmant** [comment]
@rettigs I'll wait on that then.

**Comment by armiller** [comment]
We should close this pr and reopen it when @rettigs is ready.

**Comment by jordane** [comment]
@armiller no need to close. Just rebase the branch when master is in a good state.

**Comment by armiller** [comment]
My reasoning is we have a massive number of open prs and it would be good to only have prs open when they are ready to be reviewed and merged. As far as cookbooks go.

**Comment by jordane** [comment]
@armiller I'd be okay if an issue were opened. If this PR is closed and nothing else left open, we'll quickly forget about it.

**Pull request closed without merging**
