### PR TITLE
Test Kitchen Config Refactor

### PR DESCRIPTION
**Pull request by zwall-bp**
All tests green

### CODE REVIEW

**Comment by zwall-bp** [comment]
I'm getting a failed tests due to the nagios cookbook's .rubocop file.

**Comment by ramereth** [comment]
> I'm getting a failed tests on GH due to the nagios cookbook's .rubocop file. Working on this locally has no issues.

You removed the exclusions in the rubocop.yml instead of just the chef specific config that needed to be removed.

**Comment by ramereth** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v5.2.2.  Have a nice day!

**Pull request merged**
